import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/components/Navbar";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Rental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ `${inter.className}` }>
        <Navbar />
        <div className="max-w-[1500px] mx-auto relative">
          { children }
        </div>
        <Footer />
      </body>
    </html>
  );
}
